version: '3'

services:
  redis:
    image: redis:latest
    container_name: news-agg-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
